// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using E_ETL_electiva1.Entities.Models.Dwh.Dims;
namespace E_ETL_electiva1.Entities.Models.Dwh.Facts;

public partial class Opinione
{
    public int IdOpinion { get; set; }

    public string IdProducto { get; set; } = null!;

    public string? IdCliente { get; set; }

    public int? IdRedSocial { get; set; }

    public int? IdFuente { get; set; }

    public DateOnly Fecha { get; set; }

    public string? Clasificacion { get; set; }

    public byte? PuntajeSatisfaccion { get; set; }

    public virtual Cliente? IdClienteNavigation { get; set; }

    public virtual Fuente? IdFuenteNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; } = null!;

    public virtual RedesSociale? IdRedSocialNavigation { get; set; }
}