// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using E_ETL_electiva1.api.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace E_ETL_electiva1.api.context
{
    public partial interface Iopiniones_de_clientesDBContextProcedures
    {
        Task<int> sp_etl_insert_opinionAsync(string? idCliente, string? idProducto, int? idRedSocial, DateOnly? fecha, string? comentario, string? clasificacion, byte? puntajeSatisfaccion, string? fuente, OutputParameter<int?> idOpinion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_insert_opinion_sinRedAsync(string? idCliente, string? idProducto, DateOnly? fecha, string? comentario, string? clasificacion, byte? puntajeSatisfaccion, string? fuente, OutputParameter<int?> idOpinion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_categoriaAsync(string? nombreCategoria, OutputParameter<int?> idCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_clienteAsync(string? nombre, string? email, string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_cliente_IdOnlyAsync(string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_fuente_datoAsync(string? idFuente, int? idTipoFuente, DateOnly? fechaCarga, OutputParameter<string> idFuenteOut, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_productoAsync(string? idProducto, string? nombre, int? idCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_producto_IdProductoAsync(string? idProducto, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_etl_upsert_red_socialAsync(string? nombreRedSocial, OutputParameter<int?> idRedSocial, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_etl_upsert_tipo_fuenteResult>?> sp_etl_upsert_tipo_fuenteAsync(string? nombreTipo, OutputParameter<int?> idTipoFuente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
