// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using E_ETL_electiva1.api.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace E_ETL_electiva1.api.context
{
    public partial class opiniones_de_clientesDBContext
    {
        private Iopiniones_de_clientesDBContextProcedures? _procedures;

        public virtual Iopiniones_de_clientesDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new opiniones_de_clientesDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Iopiniones_de_clientesDBContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class opiniones_de_clientesDBContextProcedures : Iopiniones_de_clientesDBContextProcedures
    {
        private readonly opiniones_de_clientesDBContext _context;

        public opiniones_de_clientesDBContextProcedures(opiniones_de_clientesDBContext context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_etl_insert_opinionAsync(string? idCliente, string? idProducto, int? idRedSocial, DateOnly? fecha, string? comentario, string? clasificacion, byte? puntajeSatisfaccion, string? fuente, OutputParameter<int?> idOpinion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdOpinion = new SqlParameter
            {
                ParameterName = "IdOpinion",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idOpinion?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 10,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 10,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdRedSocial",
                    Value = idRedSocial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Fecha",
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Comentario",
                    Size = 400,
                    Value = comentario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Clasificacion",
                    Size = 50,
                    Value = clasificacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PuntajeSatisfaccion",
                    Value = puntajeSatisfaccion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "Fuente",
                    Size = 40,
                    Value = fuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterIdOpinion,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_insert_opinion] @IdCliente = @IdCliente, @IdProducto = @IdProducto, @IdRedSocial = @IdRedSocial, @Fecha = @Fecha, @Comentario = @Comentario, @Clasificacion = @Clasificacion, @PuntajeSatisfaccion = @PuntajeSatisfaccion, @Fuente = @Fuente, @IdOpinion = @IdOpinion OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            idOpinion?.SetValue(parameterIdOpinion.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_insert_opinion_sinRedAsync(string? idCliente, string? idProducto, DateOnly? fecha, string? comentario, string? clasificacion, byte? puntajeSatisfaccion, string? fuente, OutputParameter<int?> idOpinion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdOpinion = new SqlParameter
            {
                ParameterName = "IdOpinion",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idOpinion?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 10,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 10,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Fecha",
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Comentario",
                    Size = -1,
                    Value = comentario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Clasificacion",
                    Size = 50,
                    Value = clasificacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PuntajeSatisfaccion",
                    Value = puntajeSatisfaccion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "fuente",
                    Size = 40,
                    Value = fuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterIdOpinion,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_insert_opinion_sinRed] @IdCliente = @IdCliente, @IdProducto = @IdProducto, @Fecha = @Fecha, @Comentario = @Comentario, @Clasificacion = @Clasificacion, @PuntajeSatisfaccion = @PuntajeSatisfaccion, @fuente = @fuente, @IdOpinion = @IdOpinion OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            idOpinion?.SetValue(parameterIdOpinion.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_categoriaAsync(string? nombreCategoria, OutputParameter<int?> idCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdCategoria = new SqlParameter
            {
                ParameterName = "IdCategoria",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idCategoria?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NombreCategoria",
                    Size = 100,
                    Value = nombreCategoria ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterIdCategoria,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_categoria] @NombreCategoria = @NombreCategoria, @IdCategoria = @IdCategoria OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            idCategoria?.SetValue(parameterIdCategoria.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_clienteAsync(string? nombre, string? email, string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Nombre",
                    Size = 150,
                    Value = nombre ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 254,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 6,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_cliente] @Nombre = @Nombre, @Email = @Email, @IdCliente = @IdCliente", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_cliente_IdOnlyAsync(string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 6,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_cliente_IdOnly] @IdCliente = @IdCliente", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_fuente_datoAsync(string? idFuente, int? idTipoFuente, DateOnly? fechaCarga, OutputParameter<string> idFuenteOut, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdFuenteOut = new SqlParameter
            {
                ParameterName = "IdFuenteOut",
                Size = 20,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idFuenteOut?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdFuente",
                    Size = 20,
                    Value = idFuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdTipoFuente",
                    Value = idTipoFuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FechaCarga",
                    Value = fechaCarga ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterIdFuenteOut,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_fuente_dato] @IdFuente = @IdFuente, @IdTipoFuente = @IdTipoFuente, @FechaCarga = @FechaCarga, @IdFuenteOut = @IdFuenteOut OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            idFuenteOut?.SetValue(parameterIdFuenteOut.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_productoAsync(string? idProducto, string? nombre, int? idCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 6,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Nombre",
                    Size = 150,
                    Value = nombre ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdCategoria",
                    Value = idCategoria ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_producto] @IdProducto = @IdProducto, @Nombre = @Nombre, @IdCategoria = @IdCategoria", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_producto_IdProductoAsync(string? idProducto, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 6,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_producto_IdProducto] @IdProducto = @IdProducto", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_etl_upsert_red_socialAsync(string? nombreRedSocial, OutputParameter<int?> idRedSocial, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdRedSocial = new SqlParameter
            {
                ParameterName = "IdRedSocial",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idRedSocial?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NombreRedSocial",
                    Size = 100,
                    Value = nombreRedSocial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterIdRedSocial,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_etl_upsert_red_social] @NombreRedSocial = @NombreRedSocial, @IdRedSocial = @IdRedSocial OUTPUT", sqlParameters, cancellationToken ?? CancellationToken.None);

            idRedSocial?.SetValue(parameterIdRedSocial.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_etl_upsert_tipo_fuenteResult>?> sp_etl_upsert_tipo_fuenteAsync(string? nombreTipo, OutputParameter<int?> idTipoFuente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterIdTipoFuente = new SqlParameter
            {
                ParameterName = "IdTipoFuente",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = idTipoFuente?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NombreTipo",
                    Size = 100,
                    Value = nombreTipo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterIdTipoFuente,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_etl_upsert_tipo_fuenteResult>("EXEC @returnValue = [dbo].[sp_etl_upsert_tipo_fuente] @NombreTipo = @NombreTipo, @IdTipoFuente = @IdTipoFuente OUTPUT", sqlParameters, cancellationToken);

            idTipoFuente?.SetValue(parameterIdTipoFuente.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
