// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using E_ETL_electiva1.Entities.Models.Dwh.Facts;

namespace E_ETL_electiva1.Entities.Models.Dwh.Dims;

public partial class RedesSociale
{
    public int IdRedSocial { get; set; }

    public string NombreRedSocial { get; set; } = null!;

    public virtual ICollection<Opinione> Opiniones { get; set; } = new List<Opinione>();
}