// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Clientes
{
    public string IdCliente { get; set; } = null!;

    public string? Nombre { get; set; }

    public string? Email { get; set; }

    public virtual ICollection<Opiniones> Opiniones { get; set; } = new List<Opiniones>();
}