// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Fuente_Datos
{
    public string IdFuente { get; set; } = null!;

    public int IdTipoFuente { get; set; }

    public DateTime FechaCarga { get; set; }

    public virtual Tipos_Fuente IdTipoFuenteNavigation { get; set; } = null!;
}
