// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Opiniones
{
    public int IdOpinion { get; set; }

    public string? IdCliente { get; set; }

    public string IdProducto { get; set; } = null!;

    public int? IdRedSocial { get; set; }

    public DateOnly Fecha { get; set; }

    public string? Comentario { get; set; }

    public string? Clasificacion { get; set; }

    public byte? PuntajeSatisfaccion { get; set; }

    public string? Fuente { get; set; }

    public virtual Clientes? IdClienteNavigation { get; set; }

    public virtual Productos IdProductoNavigation { get; set; } = null!;

    public virtual Redes_Sociales? IdRedSocialNavigation { get; set; }
}