// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Productos
{
    public string IdProducto { get; set; } = null!;

    public string? Nombre { get; set; }

    public int? IdCategoria { get; set; }

    public virtual Categorias? IdCategoriaNavigation { get; set; }

    public virtual ICollection<Opiniones> Opiniones { get; set; } = new List<Opiniones>();
}