// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Redes_Sociales
{
    public int IdRedSocial { get; set; }

    public string NombreRedSocial { get; set; } = null!;

    public virtual ICollection<Opiniones> Opiniones { get; set; } = new List<Opiniones>();
}