// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace E_ETL_electiva1.api.Models
{
    public partial class sp_etl_upsert_tipo_fuenteResult
    {
        public int IdTipoFuente { get; set; }
        [StringLength(100)]
        public string NombreTipo { get; set; } = default!;
    }
}
