// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace E_ETL_electiva1.api.Models;

public partial class Tipos_Fuente
{
    public int IdTipoFuente { get; set; }

    public string NombreTipo { get; set; } = null!;

    public virtual ICollection<Fuente_Datos> Fuente_Datos { get; set; } = new List<Fuente_Datos>();
}