// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using E_ETL_electiva1.Entities.Models.Dwh.Dims; 
using E_ETL_electiva1.Entities.Models.Dwh.Facts;

namespace E_ETL_electiva1.Data.context;

public partial class AnaliticalDbElectiva1Context : DbContext
{
    public AnaliticalDbElectiva1Context(DbContextOptions<AnaliticalDbElectiva1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Fuente> Fuentes { get; set; }

    public virtual DbSet<Opinione> Opiniones { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<RedesSociale> RedesSociales { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC27113AB826");

            entity.HasIndex(e => e.IdCliente, "IX_Clientes_IdCliente");

            entity.HasIndex(e => e.IdCliente, "UQ__Clientes__D59466436DCFFEAF").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.IdCliente)
                .HasMaxLength(6)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Fuente>(entity =>
        {
            entity.HasKey(e => e.IdFuentes).HasName("PK__Fuentes__CBCC36D345EAAC4A");

            entity.HasIndex(e => e.IdFuentes, "IX_Fuentes_IdFuentes");

            entity.Property(e => e.Fuente1)
                .HasMaxLength(100)
                .HasColumnName("Fuente");
        });

        modelBuilder.Entity<Opinione>(entity =>
        {
            entity.HasKey(e => e.IdOpinion).HasName("PK__Opinione__2F8F71D7A141C539");

            entity.ToTable(tb => tb.HasTrigger("TR_Opiniones_Insert"));

            entity.HasIndex(e => new { e.IdProducto, e.IdCliente, e.IdRedSocial, e.IdFuente }, "IX_Opiniones_Dimensiones");

            entity.Property(e => e.Clasificacion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IdCliente)
                .HasMaxLength(6)
                .IsUnicode(false);
            entity.Property(e => e.IdProducto).HasMaxLength(6);

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Opiniones)
                .HasPrincipalKey(p => p.IdCliente)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("fk_op_cliente");

            entity.HasOne(d => d.IdFuenteNavigation).WithMany(p => p.Opiniones)
                .HasForeignKey(d => d.IdFuente)
                .HasConstraintName("fk_op_fuentes");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.Opiniones)
                .HasPrincipalKey(p => p.IdProducto)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_op_producto");

            entity.HasOne(d => d.IdRedSocialNavigation).WithMany(p => p.Opiniones)
                .HasForeignKey(d => d.IdRedSocial)
                .HasConstraintName("fk_op_red_social");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC27487CB7A6");

            entity.HasIndex(e => e.IdProducto, "IX_Productos_IdProducto");

            entity.HasIndex(e => e.IdProducto, "UQ__Producto__09889211237C3621").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.IdProducto).HasMaxLength(6);
            entity.Property(e => e.Nombre)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.NombreCategoria)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RedesSociale>(entity =>
        {
            entity.HasKey(e => e.IdRedSocial).HasName("PK__Redes_So__FCCC51148D49A722");

            entity.ToTable("Redes_Sociales");

            entity.HasIndex(e => e.IdRedSocial, "IX_Redes_Sociales_IdRedSocial");

            entity.HasIndex(e => e.NombreRedSocial, "UQ__Redes_So__37FD7CC8DD62AFAD").IsUnique();

            entity.Property(e => e.NombreRedSocial)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}