// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using E_ETL_electiva1.Entities.Models.Dwh.Facts;
using E_ETL_electiva1.Entities.Models.Dwh.Dims;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace E_ETL_electiva1.Data.context
{
    public partial class AnaliticalDbElectiva1Context
    {
        private IAnaliticalDbElectiva1ContextProcedures? _procedures;

        public virtual IAnaliticalDbElectiva1ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AnaliticalDbElectiva1ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAnaliticalDbElectiva1ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AnaliticalDbElectiva1ContextProcedures : IAnaliticalDbElectiva1ContextProcedures
    {
        private readonly AnaliticalDbElectiva1Context _context;

        public AnaliticalDbElectiva1ContextProcedures(AnaliticalDbElectiva1Context context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_upsert_clienteAsync(string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 6,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_upsert_cliente] @IdCliente = @IdCliente", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_upsert_fuenteAsync(string? fuente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Fuente",
                    Size = 100,
                    Value = fuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_upsert_fuente] @Fuente = @Fuente", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_upsert_opinionAsync(int? idOpinion, string? idProducto, string? idCliente, int? idRedSocial, int? idFuente, DateOnly? fecha, byte? puntajeSatisfaccion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdOpinion",
                    Value = idOpinion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 6,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdCliente",
                    Size = 6,
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdRedSocial",
                    Value = idRedSocial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IdFuente",
                    Value = idFuente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Fecha",
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "PuntajeSatisfaccion",
                    Value = puntajeSatisfaccion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_upsert_opinion] @IdOpinion = @IdOpinion, @IdProducto = @IdProducto, @IdCliente = @IdCliente, @IdRedSocial = @IdRedSocial, @IdFuente = @IdFuente, @Fecha = @Fecha, @PuntajeSatisfaccion = @PuntajeSatisfaccion", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_upsert_productoAsync(string? idProducto, string? nombre, int? idCategoria, string? nombreCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdProducto",
                    Size = 6,
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Nombre",
                    Size = 150,
                    Value = nombre ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IdCategoria",
                    Value = idCategoria ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NombreCategoria",
                    Size = 100,
                    Value = nombreCategoria ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_upsert_producto] @IdProducto = @IdProducto, @Nombre = @Nombre, @IdCategoria = @IdCategoria, @NombreCategoria = @NombreCategoria", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_upsert_red_socialAsync(string? nombreRedSocial, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NombreRedSocial",
                    Size = 100,
                    Value = nombreRedSocial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_upsert_red_social] @NombreRedSocial = @NombreRedSocial", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
