// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using E_ETL_electiva1.Entities.Models.Dwh.Dims;
using E_ETL_electiva1.Entities.Models.Dwh.Facts;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace E_ETL_electiva1.Data.context
{
    public partial interface IAnaliticalDbElectiva1ContextProcedures
    {
        Task<int> sp_upsert_clienteAsync(string? idCliente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_upsert_fuenteAsync(string? fuente, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_upsert_opinionAsync(int? idOpinion, string? idProducto, string? idCliente, int? idRedSocial, int? idFuente, DateOnly? fecha, byte? puntajeSatisfaccion, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_upsert_productoAsync(string? idProducto, string? nombre, int? idCategoria, string? nombreCategoria, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_upsert_red_socialAsync(string? nombreRedSocial, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
